name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.10.0 flake8==7.1.1 isort==5.13.2

      - name: Check file formatting
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Run Black
        run: black . --check --line-length=150

      - name: Run Flake8
        run: flake8 . --max-line-length=150

      - name: Run isort
        run: isort . --check-only --profile=black
